### ISSUE TITLE
Fantastic work! Can you make the application a multilingual version?

### ISSUE THREAD

**Issue by hexart** [MSzturc/ThinkpadAssistant#1]
I'd very much like to provide a Chinese language pack.

**Comment by MSzturc** [comment]
Great Idea! Do i have to create language profiles for all three Chinese languages?

![image](https://user-images.githubusercontent.com/4275753/81174065-71349700-8fa1-11ea-8f54-49c270f0fb72.png)

**Comment by hexart** [comment]
[zh-Hans.lproj.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4588025/zh-Hans.lproj.zip)
Here‘s the simplified Chinese language pack, its working.

**Comment by hexart** [comment]
I'll draw a vector menu icon later, wish it could surprise you.

**Comment by hexart** [comment]
I found a issue, microphone mute function works, but the light on F4 key isn't on, does this happen to you?

**Comment by MSzturc** [comment]
Wow... :-)
Until now i didn't noticed that there is a light on F4 key, thats cool. Now i have to find out how to activate it

**Comment by hexart** [comment]
<img width="478" alt="thinkpadkeyboard" src="https://user-images.githubusercontent.com/5528016/81210585-afaf6d80-9004-11ea-8867-f0db1133ce83.png">
How does it look? If you like it, tell me which format and what size do you need for menu icon.

**Comment by MSzturc** [comment]
Ohhh wow the icons are awesome. I need them in png format at follow sizes (for light and dark theme )

Icon size (@1x) | Icon size (@2x)
-- | --
512px × 512px (512pt × 512pt @1x) | 1024px × 1024px (512pt × 512pt @2x)
256px × 256px (256pt × 256pt @1x) | 512px × 512px (256pt × 256pt @2x)
128px × 128px (128pt × 128pt @1x) | 256px × 256px (128pt × 128pt @2x)
32px × 32px (32pt × 32pt @1x) | 64px × 64px (32pt × 32pt @2x)
16px × 16px (16pt × 16pt @1x) | 32px × 32px (16pt × 16pt @2x)

Taken form the apple style guide from here:

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by MSzturc** [comment]
I've figured out how to set and reset the F4 LED. Currently i implemented an toggle which is kind of messy since its not syncronized with muting functionality. I guess i have to write ein kext to communicate with the led from Userland

**Comment by hexart** [comment]
> I've figured out how to set and reset the F4 LED. Currently i implemented an toggle which is kind of messy since its not syncronized with muting functionality. I guess i have to write ein kext to communicate with the led from Userland
> 
> Ive commited my changes to my T460 build [here](https://github.com/MSzturc/Lenovo-T460-OpenCore/commit/8c8ad990647e62831517a216f984ba446ea9d1ea)

Super! I'll test it later.

**Comment by hexart** [comment]
[MenuIcon.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4590349/MenuIcon.zip)
Here's the image resource with both rasterized png and vectorized pdf version. I wish it could look like this.
<img width="445" alt="looks" src="https://user-images.githubusercontent.com/5528016/81247590-f9bc4180-904c-11ea-97ef-a35a7c198a08.png">

**Comment by MSzturc** [comment]
I've added the new icon for menuBar and appIcon. It's sad that apple doesn't support darkMode for appIcons so the white background icons are only used in menuBar. Big thx for the Icons.

**Comment by hexart** [comment]
The current app icon is fine, maybe I will try to redesign it few days later.

**Comment by simprecicchiani** [comment]
I added Italian language as suggested by @hexart.
Does the icon look too big on your system too?
<img width="800" alt="Schermata 2020-05-11 alle 09 47 12" src="https://user-images.githubusercontent.com/46405079/81536795-65afea00-936c-11ea-8bde-90b3c79d9ed9.png">

**Comment by MSzturc** [comment]
> I added Italian language as suggested by @hexart.
> Does the icon look too big on your system too?
> <img alt="Schermata 2020-05-11 alle 09 47 12" width="800" src="https://user-images.githubusercontent.com/46405079/81536795-65afea00-936c-11ea-8bde-90b3c79d9ed9.png">

Thx for the translation. I've merged you PR and Released a new Version of ThinkpadAssistant. In this Version I reduced the Iconsize of the Menubar Icon a bit. Have fun testing

**Comment by simprecicchiani** [comment]
> Thx for the translation. I've merged you PR and Released a new Version of ThinkpadAssistant. In this Version I reduced the Iconsize of the Menubar Icon a bit. Have fun testing

Translation works and icon looks way better now. Mic button (F4) is broke on 1.4 release, it doesn't perform any action.

**Comment by junaedahmed** [comment]
Hello @hexart ,

I am asking for some graphics help from you. You before helped this project with some cool graphics.
Could you please look at this [YogaSMC](https://github.com/zhen-zen/YogaSMC/discussions/86) project. And if you have spare time it would be great help if you could contribute some graphics there. It is a similar project like ThinkpadAssistant, but more general and covers a large Models.

Regards
Junaed

**Comment by hexart** [comment]
> Hello @hexart ,
> 
> I am asking for some graphics help from you. You before helped this project with some cool graphics.
> Could you please look at this [YogaSMC](https://github.com/zhen-zen/YogaSMC/discussions/86) project. And if you have spare time it would be great help if you could contribute some graphics there. It is a similar project like ThinkpadAssistant, but more general and covers a large Models.
> 
> Regards
> Junaed

Sure, I'll see what I can do.

**Comment by junaedahmed** [comment]
> Sure, I'll see what I can do.

Thanks a lot for your help
