### ISSUE TITLE
Mojave

### ISSUE THREAD

**Issue by bugraduz** [MSzturc/ThinkpadAssistant#13]
Please give me new version for mojave
ı am using mojave

**Comment by joshuaseltzer** [comment]
I'd also love to see this become compatible with Mojave (10.14) but I understand that it might not be possible if you're utilizing 10.15 APIs.

If not, a build for 10.14 would be very much welcome!

**Comment by MSzturc** [comment]
10.14.6 might work without blowing up the filesize to much. But i dont have an running macOS to test.

I've attached a build for 10.14.6 plz test and report me any bugs

[ThinkpadAssistant-10.14.6.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4685319/ThinkpadAssistant-10.14.6.zip)

**Comment by joshuaseltzer** [comment]
@MSzturc thank you for putting that together - the application itself seems to launch and run as expected.  However, I'm using a configuration provided by @Sniki (who I see is working with you in issue #12) so it appears with my configuration things aren't working quite right actually make the changes.

But the app you compiled at least runs on the machine.  Once Sniki pushes updates to the keyboard configuration, I'll be able to properly test.

I must stay on Mojave for compatibility reasons, so in the future if you can provide separate builds for 10.14 that would be awesome.  This app looks really cool - nice work!!

**Comment by MSzturc** [comment]
Closed v1.7.0 now officially support's Mojave 10.14.6

**Comment by joshuaseltzer** [comment]
Thank you so much!
