### ISSUE TITLE
New Icons for Keyboard Backlight

### ISSUE THREAD

**Issue by MSzturc** [MSzturc/ThinkpadAssistant#16]
@hexart @EETagent @tylernguyen @Sniki
To have a central space to discuss the keyboard backlight icon design with @hexart i've opened a new Issue, feel free to give him all the input you like, he will design the new hud.

**Comment by MSzturc** [comment]
Here is an overview of the current used icons:

![image](https://user-images.githubusercontent.com/4275753/83038024-ca419900-a03c-11ea-9b60-00005d2b1e28.png)

**Comment by EETagent** [comment]
My personal favourite design is proposal from @Sniki 

<img width="114" alt="82956612-7342b200-9fb1-11ea-90d1-8140ee3f8bec" src="https://user-images.githubusercontent.com/20557318/83041436-c31c8a00-a040-11ea-8eb0-f73177f3fc98.png"> <img width="110" alt="82956583-62923c00-9fb1-11ea-8591-2aa15f109436" src="https://user-images.githubusercontent.com/20557318/83041841-33c3a680-a041-11ea-8529-771223289c5d.png">


The design is in the spirit of Apple and is in line with the backlight control style on Windows

The turned off design will need to be reworked. Prohibitory sign looks like some error ...  It might be good to use Apple's approach, but I think it's too empty.
<img width="112" alt="82956836-f9f78f00-9fb1-11ea-9cee-078d8d25194f" src="https://user-images.githubusercontent.com/20557318/83041941-51910b80-a041-11ea-9428-86a1a9b448c3.png"> <img width="112" alt="82955709-b00da980-9faf-11ea-9336-6c85ae52cba7" src="https://user-images.githubusercontent.com/20557318/83042244-b64c6600-a041-11ea-9b56-b556bbbce487.png">

**Comment by hexart** [comment]
<img width="1118" alt="backlit" src="https://user-images.githubusercontent.com/5528016/83043636-aea6b480-a075-11ea-8329-d4b545552516.png">
I‘d prefer using Apple’s design language for this icon, how about its look?

**Comment by tylernguyen** [comment]
@hexart That looks pretty good! Is there a way to make dim and bright look a bit more different though? They look fairly similar.

**Comment by EETagent** [comment]
> <img alt="backlit" width="1118" src="https://user-images.githubusercontent.com/5528016/83043636-aea6b480-a075-11ea-8329-d4b545552516.png">
> 
> I‘d prefer using Apple’s design language for this icon, how about its look?

Good. Apple uses the line as an indicator of brightness though. Therefore, I prefer the proposal above
<img width="110" alt="82955786-cddb0e80-9faf-11ea-8e5c-68b900da7cf7" src="https://user-images.githubusercontent.com/20557318/83044705-d7628600-a044-11ea-9dac-f566b042683e.png">

**Comment by hexart** [comment]
First of all, unlike apple’s native icon, the function in Thinkpad assistant isn’t the function with fine-tuning, I think that why @MSzturc add text label under it to make it looks more balanced.
Second, the purpose of the HUD icon is to give us abstract symbolic visual feedback. As long as it gives us enough information about where we are, I think that’s exactly what we want.
[backlitoff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4690221/backlitoff.pdf)
[backliton.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4690222/backliton.pdf)
[backlitdim.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4690223/backlitdim.pdf)

**Comment by tylernguyen** [comment]
@hexart I agree with you. And honestly I do not mind too much one way or another. The current icons have already satisfied me. You are doing a great job and it's up to you to decide in the end!

**Comment by Sniki** [comment]
Personally both my and @hexart draft are my two favorites and im perfectly fine on which one you guys pick.

I like the @hexart idea as well for doing the change on the HUD icon so it has shorter lines for (dim) and longer lines for (bright) instead of putting two bars on the bottom whether you want or don't want text.

So @hexart you have my +1 vote, thanks for the design.

**Comment by MSzturc** [comment]
@hexart I've tried your new icons in Thinkpad Assistant 

![toogleBacklight](https://user-images.githubusercontent.com/4275753/83049898-fc0e2c00-a04b-11ea-9356-a4f47b04f588.gif)

It's a personal preference but don't you think that the free space between the icon and the text is too big?

**Comment by Sniki** [comment]
> @hexart I've tried your new icons in Thinkpad Assistant
> 
> ![toogleBacklight](https://user-images.githubusercontent.com/4275753/83049898-fc0e2c00-a04b-11ea-9356-a4f47b04f588.gif)
> 
> It's a personal preference but don't you think that the free space between the icon and the text is too big?

Yes, that's too small in my opinion, i would almost double the size of the icon there.

**Comment by hexart** [comment]
Yes it's too small, I'll download another icon in your source code as a reference.

**Comment by EETagent** [comment]
Since all the proposals are perfect and the community has agreed on a @hexart  proposal, I am also in favour of it. Really great job, it never occurred to me that I could one day use functional ThinkPad keys even in macOS

**Comment by hexart** [comment]
[backlitoff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4690464/backlitoff.pdf)
[backliton.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4690466/backliton.pdf)
[backlitdim.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4690470/backlitdim.pdf)
Try these again, please

**Comment by Sniki** [comment]
@MSzturc @hexart since we are touching the roof of perfection of the ThinkPad Keyboards:
Do you guys think it would be great to also have a Caps Lock HUD since there is no light on the Caps Lock button it's hard to know if it's on or Off unless you text ?

**Comment by tylernguyen** [comment]
@Sniki 

That sounds great! The thing though is the that some ThinkPads do the have the CapsLk LED, such as my x1c6. So that in adding support, there would need to be an option to turn off CapsLK HUD for machines who already have an LED and prefer not have an HUD. 

In other cases, I could just not add the ACPI patch for CapsLK. But since CapsLk is handled via ADB, not EC. I cannot do so.

**Comment by hexart** [comment]
> @MSzturc @hexart since we are touching the roof of perfection of the ThinkPad Keyboards:
> Do you guys think it would be great to also have a Caps Lock HUD since there is no light on the Caps Lock button it's hard to know if it's on or Off unless you text ?

Sorry, I don't think so. Imagine that you're typing an important manuscript, you need to switch Capslock on and off very frequently, the HUD will drive you crazy.

**Comment by Sniki** [comment]
> > @MSzturc @hexart since we are touching the roof of perfection of the ThinkPad Keyboards:
> > Do you guys think it would be great to also have a Caps Lock HUD since there is no light on the Caps Lock button it's hard to know if it's on or Off unless you text ?
> 
> Sorry, I don't think so. Imagine that you're typing an important manuscript, you need to switch Capslock on and off very frequently, the HUD will drive you crazy.

Well i can agree on this and that can turn out to be a PITA.

**Comment by hexart** [comment]
> @hexart I've tried your new icons in Thinkpad Assistant
> 
> ![toogleBacklight](https://user-images.githubusercontent.com/4275753/83049898-fc0e2c00-a04b-11ea-9356-a4f47b04f588.gif)
> 
> It's a personal preference but don't you think that the free space between the icon and the text is too big?

<img width="1118" alt="83043636-aea6b480-a075-11ea-8329-d4b545552516" src="https://user-images.githubusercontent.com/5528016/83053947-2d0a5300-a084-11ea-9ca0-65db21c311f2.png">
This is the final effect I want, if its possible, can you draw the image layout on this image? if you do, I'll adjust the icon assets once and for all.

**Comment by YBN-JUAN** [comment]
The Fn+Space keyboard backlight hotkey works normally in my T470s without ACPI patch, and I wonder if I need to apply your new _Q1F patch.

**Comment by Sniki** [comment]
> The Fn+Space keyboard backlight hotkey works normally in my T470s without ACPI patch, and I wonder if I need to apply your new _Q1F patch.

It works for all of us but the point is that we patch it to generate a specifc code that can be mapped on ThinkPad Assistant so we can add the GUI, we also add some checks so if backlight is off, the next HUD is level 1 (dim) if it is dim the next gui is (Bright) etc / vice versa (you get the idea)

**Comment by YBN-JUAN** [comment]
> > The Fn+Space keyboard backlight hotkey works normally in my T470s without ACPI patch, and I wonder if I need to apply your new _Q1F patch.
> 
> It works for all of us but the point is that we patch it to generate a specifc code that can be mapped on ThinkPad Assistant so we can add the GUI, we also add some checks so if backlight is off, the next HUD is level 1 (dim) if it is dim the next gui is (Bright) etc / vice versa (you get the idea)

Got it. Thank you very much.

**Comment by MSzturc** [comment]
@hexart I've tried your lastest icons in Thinkpad Assistant

![backlightNew](https://user-images.githubusercontent.com/4275753/83081669-7dcc7c80-a081-11ea-959e-979ed1de91b6.gif)

Looks awesome!

**Comment by hexart** [comment]
Better move it down a little bit, I'll modify it later.

**Comment by hexart** [comment]
> @hexart I've tried your lastest icons in Thinkpad Assistant
> Looks awesome!

Hi, I moved them down to 134px and make sure it's in the precise position.
[backlitdim.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4693892/backlitdim.pdf)
[backlitoff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4693895/backlitoff.pdf)
[backliton.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4693896/backliton.pdf)
<img width="290" alt="example" src="https://user-images.githubusercontent.com/5528016/83111393-19e49b00-a0f7-11ea-9856-74431a84ea41.png">

**Comment by hexart** [comment]
This is the Wi-Fi icon in apple's installer, what do you guys think?
![IMG_3247](https://user-images.githubusercontent.com/5528016/83113327-1999cf00-a0fa-11ea-8ad4-8e4a000fc0e5.PNG)

**Comment by Sniki** [comment]
> This is the Wi-Fi icon in apple's installer, what do you guys think?
> ![IMG_3247](https://user-images.githubusercontent.com/5528016/83113327-1999cf00-a0fa-11ea-8ad4-8e4a000fc0e5.PNG)

Yes please !,

Let’s have an Apple standard across all icons

**Comment by MSzturc** [comment]
Here are the new Icons inside Thinkpad Assistant

![backlightNew](https://user-images.githubusercontent.com/4275753/83129550-412e6e80-a0dd-11ea-8453-399f892cb082.gif)

**Comment by EETagent** [comment]
@MSzturc  @hexart  

Perfect

**Comment by MSzturc** [comment]
@hexart 
This should help you fitting the images to the HUD size in the future
![image](https://user-images.githubusercontent.com/4275753/83131957-f6165a80-a0e0-11ea-97c3-f09b62d35fa7.png)

**Comment by Sniki** [comment]
> Here are the new Icons inside Thinkpad Assistant
> 
> ![backlightNew](https://user-images.githubusercontent.com/4275753/83129550-412e6e80-a0dd-11ea-8453-399f892cb082.gif)

This one looks perfect 👌

**Comment by Sniki** [comment]
@MSzturc i have a user that reported a small issue with the Microphone Mute LED after wake from sleep.
If mic is muted and you put laptop to sleep, after you wake it, the mic will remain muted but the LED is turned of, is it possible to tweak the led code for such check as we did with Keyboard Backlight ?
Quote:
```
The Thinkpad Assistant utility is great, I just found one issue and I am not sure it is an app bug or a problem with SSDT. 

When I mute the microphone with fn+f4 the small led on f4 lights on, put the Thinkpad to sleep, wake it up again the small led on f4 is off but the microphone is still muted according to Thinkpad Assistant (pressing fn+f says it switched to unmuted).
```

**Comment by hexart** [comment]
> @hexart
> This should help you fitting the images to the HUD size in the future
> ![image](https://user-images.githubusercontent.com/4275753/83131957-f6165a80-a0e0-11ea-97c3-f09b62d35fa7.png)

Got it!
[backlitdim.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4696014/backlitdim.pdf)
[backliton.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4696015/backliton.pdf)
[backlitoff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4696016/backlitoff.pdf)

**Comment by MSzturc** [comment]
@Sniki 
It's a problem in ACPI. You have to restore LED State after wakeup. You have to patch _WAK and inside you have to restore LED state ( we created an Variable which should be still present after wakeup ). Have a look here for reference : https://github.com/zhtengw/EFI-for-X1C6-hackintosh/blob/e73ddb21e1192990e3e2156f3613b735bf71de75/ACPI/SSDT-SLPWAK-X1C6.dsl

**Comment by Sniki** [comment]
> @Sniki 
> 
> It's a problem in ACPI. You have to restore LED State after wakeup. You have to patch _WAK and inside you have to restore LED state ( we created an Variable which should be still present after wakeup ). Have a look here for reference : https://github.com/zhtengw/EFI-for-X1C6-hackintosh/blob/e73ddb21e1192990e3e2156f3613b735bf71de75/ACPI/SSDT-SLPWAK-X1C6.dsl

Thanks for the clarification.

I did post an issue where i asked a few questions on your T460 repository, i would like to have a summary for those as well like you explained this one (when you have time for it).

Thanks for all.

**Comment by hexart** [comment]
<img width="1137" alt="wifi" src="https://user-images.githubusercontent.com/5528016/83248928-6358e700-a1d8-11ea-8418-07e9eb87e30f.png">
@MSzturc @EETagent @tylernguyen @Sniki Will you guys help me to decide which is better?
[wifioff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4701143/wifioff.pdf)
[wifioff1.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4701144/wifioff1.pdf)
[wifion.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4701146/wifion.pdf)

**Comment by MSzturc** [comment]
I like this combination:

![image](https://user-images.githubusercontent.com/4275753/83251083-625c9100-a1a9-11ea-9495-614c9c01224e.png)

**Comment by EETagent** [comment]
I did a flash editing in Preview. Ignore the stripe below icon :) And the blank version looks better
![WifiOff1](https://user-images.githubusercontent.com/20557318/83251910-a1d7ad00-a1aa-11ea-9aaa-6b371613163c.png) ![WifiOff2](https://user-images.githubusercontent.com/20557318/83251912-a2704380-a1aa-11ea-8b4f-d47d4bd1c900.png)

**Comment by Sniki** [comment]
> <img alt="wifi" width="1137" src="https://user-images.githubusercontent.com/5528016/83248928-6358e700-a1d8-11ea-8418-07e9eb87e30f.png">
> 
> @MSzturc @EETagent @tylernguyen @Sniki
> I made two wifi-off icons, will you guys help me to decide which is better?
> 
> [wifioff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4701143/wifioff.pdf)
> [wifioff1.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4701144/wifioff1.pdf)
> [wifion.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4701146/wifion.pdf)

My choice is the same as @MSzturc 
The black one doesn’t look right, the blank one looks like native and resembles Apple guidelines.

**Comment by hexart** [comment]
> My choice is the same as @MSzturc
> The black one doesn’t look right, the blank one looks like native and resembles Apple guidelines.
Same as you, let the author do the honor;)

**Comment by MSzturc** [comment]
I've added the new WiFi and the updated Backlight Icons into Thinkpad Assistant! Thx for the good work @hexart
