### ISSUE TITLE
[Feature request] Automatic updates

### ISSUE THREAD

**Issue by igorkulman** [MSzturc/ThinkpadAssistant#26]
It would be great to have some kind of automatic updates for the app.

The easiest way would to to add the app to `brew cask`, for the people (like me) that preffer installing everything from `brew` and then just updating the  `brew cask` definition with every release. It is quite a simple process, running 1 script and entering the new version number, can be done by anyone not only you.

The harder way would be adding [Sparkle](https://github.com/sparkle-project/Sparkle).

**Comment by tylernguyen** [comment]
@igorkulman This would be great. However, I think the brew cask would be rejected under the clause that the app is too obscure:
```
The Cask is for an app that is too obscure. Examples:

    A self-submitted app from a GitHub repository that is not notable enough (under 30 forks, 30 watchers, and 75 stars).
```

See https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md

**Comment by igorkulman** [comment]
Maybe a custom tap? https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by tylernguyen** [comment]
@igorkulman That seems like it would take the same amount of effort as `Sparkle` and isn't really user friendly to everyone.

I'm working on adding `Sparkle` support to `ThinkpadAssistant` since I think it's just a cleaner option overall.
I will create a pull request when it's ready and tested.

**Comment by tylernguyen** [comment]
@MSzturc I am trying to implement `Sparkle` auto-updater and I need your help. Per support [doc](https://sparkle-project.org/documentation/), we need to create an `appcast.xml` to keep track of release for `Sparkle` to check against. Now, I do not have permission to the repo so I cannot do this myself, but there are two options for you to choose from:

1. We can host `appcast.xml` using GitHub Pages per this implementation: https://gist.github.com/huangyq23/668e6d6fcccf714e802a

So each time there's a new update, you would run the included bash scripts to bump the version and generate a new `appcast.xml` which can then be pushed to the GitHub Pages branch of the project.

2. This is the easier option if it works, there's a repo App called [Sparkhub Appcast](https://github.com/marketplace/sparklehub-appcast) which automatically generates and update `appcast.xml` for you.

Whichever you choose, could you please setup an `appcast.xml` file for which I can test the auto-updater against?

**Comment by MSzturc** [comment]
@tylernguyen  Great to hear. Do I still need to provide an appcast.xml?

**Comment by tylernguyen** [comment]
@MSzturc Yes. Use the SparkHub Appcast app from GitHub Marketplace. It's very easy.

**Comment by MSzturc** [comment]
@tylernguyen 

AppCast.xml
https://updates.sparklehub.io/v1/sparkle/appcasts/f2e83cc9-d9c1-451e-b1a3-5b551e225184/macos.xml

I've tested the build workflow and it seams to work :-)

**Comment by EETagent** [comment]
From Sparkle documentation:
> No sandboxing. Sparkle 1.x can't update sandboxed apps. However, Sparkle 2.x can.

Sparkle 1 doesn't support sandboxed apps. Sparkle 2 is not documented and it's implementation would not be worth the effort in my opinion. ThinkpadAssistant gets updated rarely and most updates so far required ACPI changes. Simple alert with link to latest GitHub release would be enough.
