### ISSUE TITLE
[Feature request] Option to make prtsc key behave like right alt key

### ISSUE THREAD

**Issue by zombillano** [MSzturc/ThinkpadAssistant#27]
Hi there! I wanted to know if it is possible to add the functionality of right alt key to the prtsc key. I've switched from a MBP to a T480 and I kind of miss the right alt key. I'm solving my problem using an app called karabiner but it would be awesome if it can be added to thinkpad assistant, that way I would only need 1 app for key function reasigment. Thanks in advance!

**Comment by tylernguyen** [comment]
@zombillano That's to be patched via ACPI, not ThinkpadAssistant.

See reference table here: https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/references/ApplePS2ToADBMap.h

You can checkout some examples mapping other keys here: https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/SSDT-Keyboard.dsl
