### ISSUE TITLE
[Feature request] Capslock indicator

### ISSUE THREAD

**Issue by igorkulman** [MSzturc/ThinkpadAssistant#28]
The T440s, and probably other models, does not have an Capclock indicator, could you add an icon for on/off same as with sound / microphone?

**Comment by MSzturc** [comment]
We discussed this feature a couple weeks ago and decided us against an implementation. The main reason was the fact that its pretty annoying when the hud pops up and blocks your screen when you are working on for example word or excel document where you use caps lock very often.

**Comment by igorkulman** [comment]
Would you accept a PR that adds with a menu item to enabled / disable it?

**Comment by igorkulman** [comment]
Something like

<img width="298" alt="Screenshot 2020-06-22 at 16 52 04" src="https://user-images.githubusercontent.com/4746070/85301964-d0def700-b4a8-11ea-89be-a1dc4274573a.png">

and

<img width="392" alt="Screenshot 2020-06-22 at 16 52 31" src="https://user-images.githubusercontent.com/4746070/85301985-d76d6e80-b4a8-11ea-9439-add4a8350322.png">

**Comment by MSzturc** [comment]
Sure, but I would suggest that you reduce the size of the arrow a bit.
@hexart What do you think?

**Comment by igorkulman** [comment]
It is basically a random free icon from the Internet. Better icon would be needed.

**Comment by hexart** [comment]
> Sure, but I would suggest that you reduce the size of the arrow a bit.
> @hexart What do you think?

Cool! I can't agree more since we provide a caps lock switch in app menu.
I'll try to draw a pair of icons later in two days.

**Comment by MSzturc** [comment]
Thx for the pull request. As soon as we have an better icon I will merge it. TX for your contribution

**Comment by hexart** [comment]
<img width="640" alt="capslock" src="https://user-images.githubusercontent.com/5528016/85936880-56432b00-b931-11ea-9ee0-1906f296ff86.png">

I get it from iOS keyboard layout design.

**Comment by igorkulman** [comment]
> <img alt="capslock" width="640" src="https://user-images.githubusercontent.com/5528016/85936880-56432b00-b931-11ea-9ee0-1906f296ff86.png">
> 
> I get it from iOS keyboard layout design.

I think it looks OK. If you upload it I will update my PR #30

**Comment by hexart** [comment]
[capslockoff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4844968/capslockoff.pdf)
[capslockon.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4844971/capslockon.pdf)

Sorry for the delay, I've been so busy these days.

**Comment by igorkulman** [comment]
> [capslockoff.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4844968/capslockoff.pdf)
> [capslockon.pdf](https://github.com/MSzturc/ThinkpadAssistant/files/4844971/capslockon.pdf)
> 
> Sorry for the delay, I've been so busy these days.

Thanks. I updated the PR.
