### ISSUE TITLE
Popup window's style is slightly different with the system's original ones.

### ISSUE THREAD

**Issue by hexart** [MSzturc/ThinkpadAssistant#3]
![diff](https://user-images.githubusercontent.com/5528016/81311665-45580500-90b8-11ea-8292-4aef1c77d7be.jpg)

Can you tell the slightly difference between its content color and background color?
In light mode, the content color should be pure black, and the background color should be more transparent/blur and brighter;
In dark mode, the content color should be more white(but not pure white, maybe around 245-250 or so), and the background color should be more transparent/blur and darker.
Will you please try to make the looks like a native ones?

**Comment by hexart** [comment]
[ui_element_colors](https://developer.apple.com/documentation/appkit/nscolor/ui_element_colors)
I reviewed your source code (HUD.swift & ProgressHUD.swift)and did some research, find that the color you're using is apple's standard colors. But I don't get what's the visual effect of each color in its documentations, wish you can try to find a better color configurations.

**Comment by MSzturc** [comment]
Yeah, I fiddled for 2 whole days to get the layout as near as the original one. It seams that apple doesn't follow their own style guide for HUD.

**Comment by hexart** [comment]
> Yeah, I fiddled for 2 whole days to get the layout as near as the original one. It seams that apple doesn't follow their own style guide for HUD.

WOW, it's quite a challenge. Good work!

**Comment by MSzturc** [comment]
I've got the HUD Layout almost as same as the Apple ones ;-)

[ThinkpadAssistant.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4623067/ThinkpadAssistant.zip)

**Comment by hexart** [comment]
![IMG_9005](https://user-images.githubusercontent.com/5528016/81837182-18539880-9577-11ea-8c99-c8fe288bcbf5.jpg)
Hi, I have to say it's much better than before, just the transparency is a little bit less than the native one.

**Comment by hexart** [comment]
I have a suggest that you can add an "about" menu item, thus we can know current version of TA. And you can also add some copyright info on it.

**Comment by MSzturc** [comment]
Released today v1.5.0. This Version contains an about dialog.

**Comment by hexart** [comment]
> Released today v1.5.0. This Version contains an about dialog.

[ThinkpadAssistant.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4631740/ThinkpadAssistant.zip)
Update Chinese Translation.

**Comment by MSzturc** [comment]
Perfect! Added to Codebase
