### ISSUE TITLE
System HUD icon doesn't show text level but TA HUD icon does

### ISSUE THREAD

**Issue by junaedahmed** [MSzturc/ThinkpadAssistant#4]
Hi @MSzturc ,

Today I noticed that system hud only produce icon visualization no text level under the icon,
but all ThinkpadAssistant icon have text level under them like, microphone mute/ unmute, Wi-Fi enable/ disable etc. Hope you can readjust. Thanks.

best wishes,
Junaed

**Comment by hexart** [comment]
![IMG_6808 2](https://user-images.githubusercontent.com/5528016/81568309-287d4380-93d0-11ea-896c-f66eeb393837.jpg)
No offense, this is system native HUD icon with label on it when you using Magic Mouse.

**Comment by junaedahmed** [comment]
None taken. Sorry I only compared with the system volume/brightness icons.
