### ISSUE TITLE
mute inverted

### ISSUE THREAD

**Issue by 2eno** [MSzturc/ThinkpadAssistant#43]
Probably it's the wrong place for this, and maybe it's not a ThinkpadAssistant related issue, but when I press F4 for muting the microphone it says "microphone unmuted" while the LED switches on. It means my laptop starts with a muted microphone and the microphone mute key is kinda inverted for me. If its not a software bug, any idea how to fix it? Any help is appreciated. Thank you! :)

**Comment by MSzturc** [comment]
Yeah that's a  normal behaviour. It's not possible for ThinkpadAssistant to read the State of the LED. The synchronisation of the mute toggle is done in ACPI based on the Shortcut you press. Therefore it might be that the first toggle is incorrect. Furthermore it might be that the toggle state isn't right after hibernate (i never tested if it's working)
