### ISSUE TITLE
ThinkpadAssistant for High Sierra

### ISSUE THREAD

**Issue by Charlyo** [MSzturc/ThinkpadAssistant#50]
Dear @MSzturc, can this project be compiled for high sierra?

**Comment by EETagent** [comment]
@Charlyo 

Currently not, ThinkPad Assistant uses properties introduced in macOS Mojave
https://developer.apple.com/documentation/appkit/nsapplication/2967171-effectiveappearance?language=objc

**Comment by Charlyo** [comment]
Thank you for the update @EETagent. Is there any way to change the usage of those properties??

**Comment by EETagent** [comment]
Added some `@available(macOS 10.14, *)` checks and fallback to light theme when on High Sierra. Please try that, there might be a runtime error but I can't test that as I don't have 10.13

[ThinkpadAssistant.zip](https://github.com/MSzturc/ThinkpadAssistant/files/5372236/ThinkpadAssistant.zip)

**Comment by EETagent** [comment]
> Thank you very much @EETagent !! The application works but the notifications take the whole screen. 

Can you provide screenshot?

**Comment by Charlyo** [comment]
Sure, here you are!

![image](https://user-images.githubusercontent.com/7512047/95899711-35dc9680-0d91-11eb-80ff-022cb7350022.png)

**Comment by EETagent** [comment]
> Sure, here you are!

Well, this is weird. I replaced Mojave checks with macOS 11 one, to achieve same code behaviour as on High Sierra ( I am on Catalina currently ) and it works for me. `override func updateLayer() {` is somewhat not executed on your machine. 

With override func updateLayer() {
![Snímek obrazovky 2020-10-14 v 10 50 42](https://user-images.githubusercontent.com/20557318/95966494-7d076d80-0e0b-11eb-89a6-48fa6c76a73b.png)


I see that you do not have GPU acceleration working. Your dock and ThinkPad Assistant HUD are not transparent. That might be a reason why this happens. Please fix that first

**Comment by Charlyo** [comment]
I do have the black theme (upper bar and dock) activated for High Sierra. However gonna test GPU acceleration again.

**Comment by EETagent** [comment]
By dark theme you mean `defaults write -g NSWindowDarkChocolate -bool TRUE`? Or some third party modification?

**Comment by Charlyo** [comment]
I haven't never set that up using terminal commands. Rather by general settings. 
![Screen Shot 2020-10-15 at 19 54 17](https://user-images.githubusercontent.com/7512047/96167845-3f483900-0f20-11eb-8339-54098e67b489.png)

Using white bar and dock actually shows the thinkpad assistant hud icon.
![Screen Shot 2020-10-15 at 19 55 30](https://user-images.githubusercontent.com/7512047/96167979-6999f680-0f20-11eb-990c-db93fb9c0227.png)

**Comment by EETagent** [comment]
Would you try to execute this debug version using Terminal and post log?
`ThinkpadAssistant.app/Contents/MacOS/ThinkpadAssistant`

[ThinkpadAssistant.zip](https://github.com/MSzturc/ThinkpadAssistant/files/5390198/ThinkpadAssistant.zip)

**Comment by EETagent** [comment]
@Charlyo  Actually, in the future ThinkPad Assistant would get replaced by [YogaSMC](https://github.com/zhen-zen/YogaSMC). @zhen-zen even found way to use macOS's native OSD.

**Comment by Charlyo** [comment]
@EETagent Today I saw TogaSMC release 1.2.0. Should I migrate? I'm still curious if YogSMC can be used in high sierra. Will update to Catalina if strictly necessary.

Nonetheless, thank you for your previous answers.
