### ISSUE TITLE
Please it can run mojave

### ISSUE THREAD

**Issue by bugraduz** [MSzturc/ThinkpadAssistant#7]
ı use mojave 
can you run it mojave?

**Comment by MSzturc** [comment]
I've build against 10.15 since I use Catalina. I've created an untested build against 10.14.6 please Test it an report me any issues

[ThinkpadAssistant.app.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4641030/ThinkpadAssistant.app.zip)

**Comment by bugraduz** [comment]
thank you its run , but the program works incorrectly. Because when F4 light on ,seen microphone unmuted icon and microphone is active but when mic light off, seen mic muted icon and mic deactivate. it work reverse.

**Comment by MSzturc** [comment]
Well, i guess that AudioObjectGetPropertyData behaves diffrent on older MacOS Versions. Since i have no Testbench or the time to support a second operating system beside's mine i cant support older MacOS versions.
