### ISSUE TITLE
Support for Bluetooth Enable/Disable Hotkey

### ISSUE THREAD

**Issue by tylernguyen** [MSzturc/ThinkpadAssistant#9]
Firstly, thank you for your great work!

I have the X1 Carbon 6th Gen (x1c6). In my testing, I've been able to get everything to work. However, since my machines, like some others do not have the Search button but a Bluetooth one instead. I would love the additional support.

**Comment by tylernguyen** [comment]
Also, do you have a donation link? I would love to support this project, even if it's just a little.

**Comment by MSzturc** [comment]
Cool idea, didn't know that the X1 had a diffrent keyboard layout. The problem we will face is that we wont have enough buttons to map against in ssdt. This means that we have to make the binding in Thinkpad Assistant configurable. Besides Blutooth toggle, what would you bind on F11/F12 key?

**Comment by tylernguyen** [comment]
@MSzturc I'm using the same approach you did for F11. Currently, my F10 (Bluetooth) is mapped to Shift+Down. So the full Fn map would be:

Remap 1: F4 (Network) to F20 (for use with ThinkpadAssistant)
Remap 2: F5 (Brightness Down)
Remap 3: F6 (Brightness Up)
Remap 4: F7 (Dual Display) to F16 (for use with ThinkpadAssistant)
Remap 5: F8 (Network) to F17 (for use with ThinkpadAssistant)
Remap 6: F9 (Settings) to F18 (for use with ThinkpadAssistant)
Remap 7: F10 (Bluetooth) to [Shift+Down]
Remap 8: F11 (Keyboard) to [Shift+Up] *I have this set to change keyboard input in sys pref.
Remap 9: F12 (Star) to F19 (for use with ThinkpadAssistant)

Also see my [SSDT-keyboard](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/SSDT-Keyboard.dsl) for more details.

Having ThinkpadAssistant's binding be configurable would be awesome! But my priority would be native-like HUD and support for Bluetooth toggle, since that is the only left that I'm using BetterTouchTool for.

**Comment by MSzturc** [comment]
@tylernguyen 

Added Bluetooth toogle support with v1.6.0. It's bound to left shift + F17. You could use this snippet to test it:

```
// Left Shift + F17
Notify (\_SB.PCI0.LPC.KBD, 0x012a)
Notify (\_SB.PCI0.LPC.KBD, 0x0368)
Notify (\_SB.PCI0.LPC.KBD, 0x01aa)
```

Have fun

**Comment by tylernguyen** [comment]
@MSzturc 

Worked perfectly! Thank you so much for adding support. Post a donation link!
